baseURL: https://analyticscentre.netlify.app/
languageCode: en-us
title: Analytics Centre
theme: "hugo-fresh-data-science"
# Put in your google analytics tracking code without quotes like this: UA-XXXXXX...
googleAnalytics: G-BQ956METEY # UA-XXXXX...

# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Put your formspree URL in like this:  https://formspree.io/f/...
  formspreeURL: "https://formspree.io/f/xayzwnkd"
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/BusinessLogomodern.png
    link: /
    brandName: Analytics Centre
    # Default width/height. Uncomment if you need to change
    width: 50
    height: 50
  
  # Web Fonts Available Here: https://fonts.google.com/
  googleFontImport: 'https://fonts.googleapis.com/css2?family=Roboto&display=swap'#'https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400&family=Work+Sans:ital,wght@1,500&display=swap'
  header_font: "Roboto"
  body_font: "Work Sans"
  
  # css
  css:
    secondary_color: "#979797" # "#F39200" "#4FC1EA" "#00efb7" "#100e0d" (Controls Buttons, Accents)
    mutedgrey_color: "#999" # "#999" # Contols writing 
    greydark_color: "#6c6d71" # "#4a4a4a" Controls Headers
    bluegrey_color: "#202020" # "#444F60" #2c3e50 (Controls Headers & Footer Background)
    navbar_color: "#202020" # "#FFF"
    navbar_text_color: "#ffffff" # #999  
  # css:
  #   secondary_color: "#979797" # "#F39200" "#4FC1EA" "#00efb7" "#100e0d" (Controls Buttons, Accents)
  #   mutedgrey_color: "#000000" # "#999" # Contols writing 
  #   greydark_color: "#000000" # "#4a4a4a" Controls Headers
  #   bluegrey_color: "#202020" # "#444F60" #2c3e50 (Controls Headers & Footer Background)
  #   navbar_color: "#ffffff" # "#FFF" "#081D4A"
  #   navbar_text_color: "#000000"
  
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbarStyle:
  navbar:
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  - title: Home
    url: /
  - title: Advisory
    url: /consulting
  - title: Testimonials
    url: /testimonials
  - title: Blog
    url: /blog
  - title: Contact Us
    url: /contact
  - title: Apply Now
    url: /applynow
    button: true
  
  applynow:
    title: Claim your free analytics consultation right now.
    subtitle: Let's have a conversation today 
    googleFormEmbed: "https://forms.office.com/r/6KnG5J0ata"
  
  contact:
    title: Contact Us
    subtitle: What can we help you with?
    buttontext: Contact Us
  
  section1_attention:
    # Main hero title
    title: "Start saving $100K/year by targeting the right customers at the right time"
    titleTextColor: "white"
    # Hero subtitle (optional)
    subtitle: "We save our clients money and time to serve the right customers using advanced analytics."
    heroBackgroundColor: "#000000c7"
    
    # Button text
    buttontext: "How it works"
    # Where the main hero button links to
    buttonlink: "/#section2"
    # Hero image (from static/images/___)
    # Can get these images from flaticon.com
    image: illustrations/mockups/nostradamus_app.jpg
    backgroundImage: illustrations/pexelspencalc.jpg #illustrations/company.jpg
   # clientstext: "Some of the clients we've helped:"
    # Footer logos (from static/images/logos/clients/___.svg)
  #  clientlogos:
  #  - systek.svg
   # - tribe.svg
   # - kromo.svg
   # - infinite.svg
   # - gutwork.svg
 
  section2_transformation:
    title: "How analytics consulting works." 
    subtitle: "Reduce costs from forecasting errors in 4 simple steps"
    # icons are located in static > images > illustrations > icons
    tile_size: is-one-quarter
    tile_height: "400px"
    tiles:
    - title: "Step 1"
      subtitle: Speak With A Consultant Today
      icon: conversation.svg
      text: Speak with one of our business consultants about your needs and how our program can help you.
    - title: "Step 2"
      subtitle: Become Better At Forecasting
      icon: forecasting.svg
      text: We work with your team to build a forecast application tailored to improve your business.
    - title: "Step 3"
      subtitle: Business Integration
      icon: collaboration.svg
      text: We integrate your new forecasting application and train your team to use it.
    - title: "Step 4"
      subtitle: Monitor Savings
      icon: monitoring.svg
      text: We help your team measure savings versus baselines. On average our clients save $100K per year.
  
  section3_interest:
    title: Get results faster
    subtitle: With your custom forecasting application
    image: illustrations/mockups/nostradamus_app.jpg
    tile_size: is-one-third
    tile_height: "200px"
    tiles:
    - title: "Get results in 60 days"
      subtitle: "Go from losing money to saving money without hiring multiple consultants or handling time-consuming project management yourself."
    - title: "Safe and Secure"
      subtitle: "You don't need to upload your data to unsecure cloud networks. The forecasting application can be deployed on your own server network."
    - title: "Our ROI Guarantee"
      subtitle: "On average we save our clients $100K per year. If we can't at least save you what you pay us, we'll give you your money back."
    
    
  section4_desire:
    title: Trusted by awesome companies like these that are saving money and improving their demand planning
    subtitle: Real results from our valued clients.
    clients:
    - name: Irma
      quote: We were able to save $100K by optimizing our supply and demand planning system using Forecasting Science. They delivered a solution in 90 days. This project was a slam dunk.
      job: Senior VP, Builder
      img: 1.png
    - name: John
      quote: We literally can't live without our new demand planning system built by Analytics Center. These guys delivered a $3.4M improvement to operations in under 6 months.
      job: CEO, Tech Company
      img: 2.png
    - name: Gary
      quote: I finally took the plunge and boy did it pay off. We got the first version of our forecasting system in 60 days. Let's just say that the ROI was immediate.
      job: Executive VP, Marathon Petroleum
      img: 3.png
  
  section5_faq: false
  
  section6_action:
    callToActionText: Would you like to be our next success story?
    buttonText: Apply now
    buttonLink: /applynow
  
  footer:
    # Logo (from /images/logos/___)
    logo: BusinessLogomodern.png
    navbarLogoWidth: "100px"
    navbarLogoHeight: "100px"
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # Icons are from Font Awesome
    socialmedia:
#    - link: https://www.linkedin.com/
#      icon: linkedin
#   - link: https://facebook.com/#
#      icon: facebook
    - link: https://twitter.com/analyticscntr
      icon: twitter
    - link: https://github.com/rahul-c1
      icon: github
    bulmalogo: false
    quicklinks:
      column1:
        title: "Advisory"
        links:
        - text: Why choose Analytics Centre?
          link: /consulting
        - text: Testimonials
          link: /testimonials
        - text: Apply to work with us
          link: /applynow
      column2:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog
          

          
